-- 作为测试用的表
 CREATE TABLE `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userName` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1


-- 系统表
饿了么评论表
    CREATE TABLE "HYF"."BIL_ELEME_EVALUATE"
    (	"ID" NUMBER(*,0) NOT NULL ENABLE,
    "SHOP_ID" VARCHAR2(30 BYTE),
    "CRAWLER_DATE" VARCHAR2(40 BYTE),
    "EVA_VALUE" VARCHAR2(500 BYTE),
    "QUALITY" VARCHAR2(30 BYTE),
    "GOODS" VARCHAR2(30 BYTE),
     CONSTRAINT "BIL_ELEME_EVALUATE_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD"  ENABLE
    ) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD" ;

饿了么活动表
    CREATE TABLE "HYF"."BIL_ELEME_ACTIVITY"
    (	"ID" NUMBER(*,0) NOT NULL ENABLE,
    "SHOP_ID" NUMBER(*,0),
    "BEGIN_DATE" VARCHAR2(30 BYTE),
    "END_DATE" VARCHAR2(30 BYTE),
    "NAME" VARCHAR2(200 BYTE),
    "STATUS" VARCHAR2(30 BYTE),
    "CONTENT" VARCHAR2(1000 BYTE),
    "CREATE_TIME" VARCHAR2(30 BYTE),
    "DESCRIPTION" VARCHAR2(500 BYTE),
    "IS_SHARE" VARCHAR2(200 BYTE),
     CONSTRAINT "BIL_ELEME_ACTIVITY_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD"  ENABLE
    ) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD" ;

饿了么账单表
    CREATE TABLE "HYF"."BIL_ELEME_BILL"
    (	"CLOSUBG_DATE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "INCOME" VARCHAR2(30 BYTE),
    "EXPENSE" VARCHAR2(30 BYTE),
    "DEDUCT_AMOUNT" VARCHAR2(30 BYTE),
    "DUE_AMOUNT" VARCHAR2(30 BYTE),
    "PAY_AMOUNT" VARCHAR2(30 BYTE),
    "PAYMENT_DATE" VARCHAR2(30 BYTE),
    "SHOP_ID" NUMBER(*,0),
     CONSTRAINT "BIL_ELEME_BILL_PK" PRIMARY KEY ("CLOSUBG_DATE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD"  ENABLE
    ) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD" ;

饿了么商品表
    CREATE TABLE "HYF"."BIL_ELEME_COMMODITY"
    (	"MESSAGE_DATE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "SHOP_ID" NUMBER(*,0),
    "FOOD_NAME" VARCHAR2(100 BYTE),
    "SALES_AMOUNT" NUMBER(30,2),
    "SALES_AMOUNT_RATE" VARCHAR2(30 BYTE),
    "SALES_VOLUME" NUMBER(*,0),
    "SALES_VOLUME_RATE" VARCHAR2(30 BYTE),
     CONSTRAINT "BIL_ELEME_COMMODITY_PK" PRIMARY KEY ("MESSAGE_DATE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD"  ENABLE
    ) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    TABLESPACE "CRMSFCDD" ;

饿了么流量表
      CREATE TABLE "HYF"."BIL_ELEME_FLOW"
       (	"FLOW_ID" VARCHAR2(130 BYTE) NOT NULL ENABLE,
    	"CRAWLER_DATE" VARCHAR2(30 BYTE),
    	"SHOP_NAME" VARCHAR2(100 BYTE),
    	"EXPOSURE_TOTAL_COUNT" NUMBER(*,0),
    	"VISITOR_NUM" NUMBER(*,0),
    	"BUYER_NUM" NUMBER(*,0),
    	 CONSTRAINT "BIL_ELEME_FLOW_PK" PRIMARY KEY ("FLOW_ID")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
      TABLESPACE "CRMSFCDD"  ENABLE
       ) SEGMENT CREATION DEFERRED
      PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
      TABLESPACE "CRMSFCDD" ;

饿了么营业表
    CREATE TABLE BIL_ELEME_SALE
    (
    SALE_ID VARCHAR2(130) NOT NULL
    , ORDER_DATE VARCHAR2(30)
    , SHOP NUMBER(*,0)
    , TOTAL_ORDER_AMOUNT NUMBER(30,2)
    , FOOD_AMOUNT NUMBER(30,2)
    , BOX_AMOUNT NUMBER(30,2)
    , DELIVER_AMOUNT NUMBER(30,2)
    , ONLINE_PAYMENT_AMOUNT NUMBER(30,2)
    , OFFLINE_PAYMENT_AMOUNT NUMBER(30,2)
    , RESTAURANT_DISCOUNT NUMBER(30,2)
    , ELEME_DISCOUNT NUMBER(30,2)
    , VALID_ORDER_COUNT NUMBER(*,2)
    , AVERAGE_PRICE NUMBER(30,2)
    , INVALID_ORDER_COUNT NUMBER(*,2)
    , LOSS_SALE_AMOUNT NUMBER(30,2)
    , CONSTRAINT BIL_ELEME_SALE_PK PRIMARY KEY
    (
    SALE_ID
    )
    ENABLE
    );